"""Regression tests for pipaudit.py -- Phase 3's auditor half for `uv.lock` (#165).

No network, and no `git`, `uv` or `uvx` either: `run()` is the seam every command
goes through, so the fake below plays all three from fixtures and records what was
asked of it. The live half -- real uv and pip-audit over a workspace, a path
dependency, a git source and a known-vulnerable pin -- is
`integration/test_pipaudit_live.py`.

Every class here is a defect the prose block this script replaced shipped with,
measured on uv 0.12.19 and pip-audit 2.10.1 before it was written:

  - the export ran in the checkout wherever `$SCRATCH/pr-<N>` did not exist, and
    exported the checkout's lockfile (`fpga-board-sim` #438: ruff 0.16.7 where the
    PR proposes 0.16.8), and the name check after it passed;
  - one unhashable line -- a workspace member, a path, a git source -- made
    `pip-audit` refuse the whole file at exit 1, its status for a finding too;
  - `pip-audit` evaluates markers against its own interpreter and drops the pins
    that do not match, absent from its JSON rather than skipped: 4 of #438's 38.

    python3 -m unittest discover -s tests -v
"""

from __future__ import annotations

import contextlib
import io
import json
import pathlib
import re
import subprocess
import sys
import tempfile
import tomllib
import unittest
from typing import Any
from unittest import mock

sys.path.insert(
    0, str(pathlib.Path(__file__).resolve().parent.parent / "skills/dependabot-audit/scripts")
)

import pipaudit
from pipaudit import entries, introduced, main, passes, write_pass

BASE = "b" * 40
PR = "pr-1"

LOCK_BASE = """\
version = 1
requires-python = ">=3.10"

[[package]]
name = "app"
version = "0.1.0"
source = { editable = "." }

[[package]]
name = "ruff"
version = "0.16.7"
source = { registry = "https://pypi.org/simple" }

[[package]]
name = "rpds-py"
version = "0.30.0"
source = { registry = "https://pypi.org/simple" }

[[package]]
name = "rpds-py"
version = "2026.6.3"
source = { registry = "https://pypi.org/simple" }

[[package]]
name = "iniconfig"
version = "2.0.0"
source = { git = "https://github.com/pytest-dev/iniconfig?tag=v2.0.0#93f5930e" }
"""

LOCK_PR = LOCK_BASE.replace('version = "0.16.7"', 'version = "0.16.8"')

# What `uv export` writes for LOCK_PR: the project and the git source left out, the
# fork pinned twice under its markers, a hash under every pin.
EXPORT_PR = """\
# This file was autogenerated by uv via the following command:
#    uv export --frozen ...
rpds-py==0.30.0 ; python_full_version < '3.11' \\
    --hash=sha256:cccc \\
    --hash=sha256:c2c2
rpds-py==2026.6.3 ; python_full_version >= '3.11' \\
    --hash=sha256:dddd
ruff==0.16.8 \\
    --hash=sha256:aaaa \\
    --hash=sha256:bbbb
"""

# The #165 shape: the same export, of the checkout's lockfile at the base.
EXPORT_CHECKOUT = EXPORT_PR.replace("ruff==0.16.8", "ruff==0.16.7")

TREE = [
    ("100644", "blob", "1" * 40, "pyproject.toml"),
    ("100644", "blob", "2" * 40, "uv.lock"),
    ("100644", "blob", "3" * 40, "packages/a/pyproject.toml"),
    ("120000", "blob", "4" * 40, "linked/pyproject.toml"),
    ("100644", "blob", "5" * 40, "src/app/__init__.py"),
    ("160000", "commit", "6" * 40, "vendored/pyproject.toml"),
]
BLOBS = {
    "1" * 40: b'[project]\nname = "app"\nversion = "0.1.0"\n',
    "2" * 40: LOCK_PR.encode(),
    "3" * 40: b'[project]\nname = "a"\nversion = "0.1.0"\n',
    "5" * 40: b"raise SystemExit('the PR's code ran')\n",
}


class Fake:
    """`git`, `uv` and `uvx`, answered from fixtures, every call recorded."""

    def __init__(
        self,
        *,
        locks: dict[str, str] | None = None,
        export: str = EXPORT_PR,
        export_fails: bool = False,
        vulns: dict[tuple[str, str], list[dict[str, Any]]] | None = None,
        skip: dict[tuple[str, str], str] | None = None,
        drop: set[tuple[str, str]] | None = None,
        refuse: bool = False,
        tree: list[tuple[str, str, str, str]] | None = None,
    ) -> None:
        self.locks = {PR: LOCK_PR, BASE: LOCK_BASE} if locks is None else locks
        self.export = export
        self.export_fails = export_fails
        self.vulns = vulns or {}
        self.skip = skip or {}
        self.drop = drop or set()
        self.refuse = refuse
        self.tree = TREE if tree is None else tree
        self.calls: list[tuple[list[str], pathlib.Path | None]] = []

    @staticmethod
    def done(argv: list[str], code: int, out: bytes = b"", err: bytes = b"") -> Any:
        return subprocess.CompletedProcess(argv, code, out, err)

    def __call__(self, argv: list[str], *, cwd: pathlib.Path | None = None) -> Any:
        self.calls.append((list(argv), cwd))
        tool, rest = argv[0], argv[1:]
        if tool == "git":
            return self.git(argv, rest)
        if tool == "uv":
            return self.uv(argv, rest)
        if tool == "uvx":
            return self.uvx(argv, rest)
        raise AssertionError(f"unexpected command {argv}")

    def git(self, argv: list[str], rest: list[str]) -> Any:
        if rest[0] == "show":
            ref, _, path = rest[1].partition(":")
            if ref in self.locks and path == "uv.lock":
                return self.done(argv, 0, self.locks[ref].encode())
            return self.done(argv, 128, err=f"fatal: invalid object name '{ref}'.\n".encode())
        if rest[0] == "ls-tree":
            if rest[-1] not in self.locks:
                return self.done(argv, 128, err=b"fatal: not a tree object\n")
            listing = "".join(f"{m} {k} {s}\t{p}\0" for m, k, s, p in self.tree)
            return self.done(argv, 0, listing.encode())
        if rest[0] == "cat-file":
            blob = BLOBS.get(rest[2])
            return self.done(argv, 0, blob) if blob is not None else self.done(argv, 128)
        if rest[0] == "rev-parse":
            return self.done(argv, 0, b"4f01a2ccb41d\n")
        raise AssertionError(f"unexpected git call {argv}")

    def uv(self, argv: list[str], rest: list[str]) -> Any:
        assert rest[0] == "export", argv
        if self.export_fails:
            return self.done(argv, 2, err=b"error: No `pyproject.toml` found\n")
        pathlib.Path(argv[argv.index("-o") + 1]).write_text(self.export, encoding="utf-8")
        return self.done(argv, 0)

    def uvx(self, argv: list[str], rest: list[str]) -> Any:
        if rest == ["pip-audit", "--version"]:
            return self.done(argv, 0, b"pip-audit 2.10.1\n")
        if self.refuse:
            err = b"ERROR:pip_audit._cli:requirement -e ./x does not contain a hash\n"
            return self.done(argv, 1, err=err)
        pins = [(n, v) for n, v, _ in entries(pathlib.Path(argv[argv.index("-r") + 1]))]
        deps = []
        for name, version in pins:
            if (name, version) in self.drop:
                continue
            dep: dict[str, Any] = {"name": name, "version": version}
            if (name, version) in self.skip:
                dep["skip_reason"] = self.skip[name, version]
            else:
                dep["vulns"] = self.vulns.get((name, version), [])
            deps.append(dep)
        report = pathlib.Path(argv[argv.index("--output") + 1])
        report.write_text(json.dumps({"dependencies": deps, "fixes": []}), encoding="utf-8")
        found = any(d.get("vulns") for d in deps)
        return self.done(argv, 1 if found else 0)


class Harness(unittest.TestCase):
    def go(self, fake: Fake, scratch: pathlib.Path | None = None) -> tuple[int, str, str]:
        """(exit status, stdout, stderr), with the scratch directory kept for reading."""
        own = scratch is None
        holder = tempfile.TemporaryDirectory() if own else contextlib.nullcontext(str(scratch))
        with holder as where:
            self.scratch = pathlib.Path(where)
            argv = ["pipaudit.py", "--scratch", where, "--ref", PR, "--base", BASE]
            out, err = io.StringIO(), io.StringIO()
            with (
                mock.patch("pipaudit.run", fake),
                mock.patch.object(sys, "argv", argv),
                contextlib.redirect_stdout(out),
                contextlib.redirect_stderr(err),
            ):
                try:
                    code: int | str | None = main()
                except SystemExit as exc:
                    code = exc.code
            self.written = {
                str(p.relative_to(self.scratch)): p.read_bytes()
                for p in self.scratch.rglob("*")
                if p.is_file()
            }
        return int(code or 0), out.getvalue(), err.getvalue()


class TestItReadsThePrAtItsRefNeverTheCheckout(Harness):
    """#165: `cd "$SCRATCH/pr-<N>"` failed wherever that worktree was never made,
    and with no `|| exit` the export ran in the user's checkout."""

    def test_the_export_runs_in_the_manifests_it_wrote(self):
        fake = Fake()
        code, _, _ = self.go(fake)
        self.assertEqual(code, 0)
        _, cwd = next(c for c in fake.calls if c[0][0] == "uv")
        self.assertIsNotNone(cwd)
        assert cwd is not None
        self.assertEqual(cwd.name, "pr-1-manifests")
        manifests = sorted(k for k in self.written if k.startswith("pr-1-manifests/"))
        self.assertEqual(
            manifests,
            [
                "pr-1-manifests/packages/a/pyproject.toml",
                "pr-1-manifests/pyproject.toml",
                "pr-1-manifests/uv.lock",
            ],
        )
        self.assertEqual(self.written["pr-1-manifests/uv.lock"], LOCK_PR.encode())

    def test_no_source_file_the_pr_ships_is_ever_written(self):
        """What is not on disk cannot run -- the tripwire in `src/` stays in git."""
        self.go(Fake())
        self.assertFalse([k for k in self.written if k.endswith(".py")])

    def test_a_symlink_and_a_submodule_are_named_not_followed(self):
        _, out, _ = self.go(Fake())
        self.assertIn("not written: linked/pyproject.toml (mode 120000", out)
        self.assertIn("not written: vendored/pyproject.toml (mode 160000", out)

    def test_a_path_that_climbs_out_is_refused(self):
        tree = [*TREE, ("100644", "blob", "3" * 40, "../escape/pyproject.toml")]
        _, out, _ = self.go(Fake(tree=tree))
        self.assertIn("not written: ../escape/pyproject.toml (not a plain relative path)", out)

    def test_every_git_call_names_a_ref_or_an_object(self):
        """No call reads the working tree: each names `pr-1`, the base, or a blob."""
        fake = Fake()
        self.go(fake)
        names = {PR, BASE, *BLOBS}
        for argv, _ in fake.calls:
            if argv[0] == "git":
                self.assertTrue(any(n in " ".join(argv) for n in names), argv)

    def test_a_ref_that_does_not_resolve_is_underivable(self):
        fake = Fake(locks={BASE: LOCK_BASE})
        code, out, err = self.go(fake)
        self.assertEqual(code, 2)
        self.assertIn("cannot read uv.lock at pr-1", err)
        self.assertFalse([c for c in fake.calls if c[0][0] in ("uv", "uvx")])
        self.assertNotIn("RESULT", out)


class TestTheExportCarriesEverythingItCan(Harness):
    def test_every_package_group_and_extra_and_nothing_unhashable(self):
        fake = Fake()
        self.go(fake)
        argv = next(c[0] for c in fake.calls if c[0][0] == "uv")
        for flag in (
            "-q",
            "--frozen",
            "--no-config",
            "--all-packages",
            "--all-groups",
            "--all-extras",
            "--no-emit-workspace",
            "--no-emit-local",
            "--no-emit-package=iniconfig",
        ):
            self.assertIn(flag, argv)

    def test_nothing_here_installs_syncs_or_runs_the_project(self):
        """`uv export --frozen` reads the lockfile; nothing else of uv's is called."""
        fake = Fake()
        self.go(fake)
        for argv, _ in fake.calls:
            joined = " ".join(argv)
            self.assertNotRegex(joined, r"\buv (?:run|sync|pip)\b|\bpip install\b", joined)
            if argv[0] == "uv":
                self.assertEqual(argv[1], "export")

    def test_what_was_left_out_is_named(self):
        _, out, _ = self.go(Fake())
        self.assertIn("app (editable)", out)
        self.assertIn("iniconfig (git)", out)

    def test_a_failed_export_is_underivable(self):
        code, _, err = self.go(Fake(export_fails=True))
        self.assertEqual(code, 2)
        self.assertIn("No `pyproject.toml` found", err)


class TestThePrsVersionsAreCheckedByVersionNotName(Harness):
    def test_an_export_of_the_pre_bump_set_is_not_a_clean_row(self):
        """The #438 reproduction: `ruff==0.16.7` exported where the PR proposes
        0.16.8. The name check this replaced passed on it."""
        code, out, _ = self.go(Fake(export=EXPORT_CHECKOUT))
        self.assertEqual(code, 1)
        self.assertIn("ruff==0.16.8   MISSING from the export", out)
        self.assertIn("RESULT: INCOMPLETE", out)
        self.assertNotIn("RESULT: CLEAN", out)

    def test_versions_are_pairs_not_a_map(self):
        """A fork added beside an unchanged one is introduced; the old one is not."""
        base = tomllib.loads(LOCK_BASE)["package"]
        pr = tomllib.loads(
            LOCK_BASE + '\n[[package]]\nname = "rpds-py"\nversion = "2026.7.1"\n'
            'source = { registry = "https://pypi.org/simple" }\n'
        )["package"]
        self.assertEqual(introduced(pr, base), [("rpds-py", "2026.7.1")])

    def test_a_moved_git_source_is_a_gap_to_name(self):
        moved = LOCK_PR.replace("#93f5930e", "#0badc0de")
        code, out, _ = self.go(Fake(locks={PR: moved, BASE: LOCK_BASE}))
        self.assertEqual(code, 1)
        self.assertIn("iniconfig: the PR moves its git source", out)


class TestEveryForkIsAudited(Harness):
    def test_markers_are_stripped_and_no_pass_names_a_package_twice(self):
        with tempfile.TemporaryDirectory() as where:
            export = pathlib.Path(where, "export.txt")
            export.write_text(EXPORT_PR, encoding="utf-8")
            split = passes(entries(export))
            self.assertEqual(len(split), 2)
            for group in split:
                names = [pipaudit.normalise(n) for n, _, _ in group]
                self.assertEqual(len(names), len(set(names)))
            written = pathlib.Path(where, "pass.txt")
            write_pass(split[0], written)
            text = written.read_text(encoding="utf-8")
        self.assertNotIn(";", text)
        self.assertIn(
            "rpds-py==0.30.0 \\\n    --hash=sha256:cccc \\\n    --hash=sha256:c2c2\n", text
        )

    def test_every_pin_is_answered_in_some_pass(self):
        _, out, _ = self.go(Fake())
        self.assertIn("3 of 3 pin(s) audited", out)
        self.assertIn("in 2 pass(es)", out)

    def test_a_pin_absent_from_every_answer_is_named(self):
        """The #438 shape: four pins `pip-audit` dropped by marker, not skipped."""
        code, out, _ = self.go(Fake(drop={("rpds-py", "0.30.0")}))
        self.assertEqual(code, 1)
        self.assertIn("NOT AUDITED, absent from pip-audit's answer: rpds-py==0.30.0", out)
        self.assertNotIn("RESULT: CLEAN", out)


class TestTheAuditorsAnswerIsItsJsonNotItsStatus(Harness):
    """Exit 1 is `pip-audit`'s status for a finding and for a refusal alike."""

    def test_a_refusal_is_underivable_never_a_finding(self):
        code, out, _ = self.go(Fake(refuse=True))
        self.assertEqual(code, 2)
        self.assertIn("does not contain a hash", out)
        self.assertIn("RESULT: UNDERIVABLE", out)
        self.assertNotIn("FOUND", out)

    def test_an_earlier_runs_json_cannot_answer_for_a_refusal(self):
        """The stale answer that matters is a plausible one: a previous run's
        finding would otherwise be reported as this run's, over a refusal."""
        earlier = {
            "dependencies": [
                {"name": "ruff", "version": "0.16.8", "vulns": [{"id": "PYSEC-OLD-1"}]}
            ],
            "fixes": [],
        }
        with tempfile.TemporaryDirectory() as where:
            # One per pass: a refusal in a pass with no stale file would exit 2
            # anyway, and mask the pass that read an old answer.
            for number in (1, 2):
                stale = pathlib.Path(where, f"pr-1-pip-audit{number}.json")
                stale.write_text(json.dumps(earlier), encoding="utf-8")
            code, out, _ = self.go(Fake(refuse=True), scratch=pathlib.Path(where))
        self.assertEqual(code, 2)
        self.assertIn("RESULT: UNDERIVABLE", out)
        self.assertNotIn("PYSEC-OLD-1", out)

    def test_an_advisory_is_found_once_and_tagged_where_the_pr_brought_it(self):
        vuln = {"id": "PYSEC-2026-1", "fix_versions": ["0.16.9"], "aliases": ["CVE-2026-1"]}
        code, out, _ = self.go(Fake(vulns={("ruff", "0.16.8"): [vuln, vuln]}))
        self.assertEqual(code, 1)
        self.assertEqual(out.count("PYSEC-2026-1"), 1, "pip-audit repeats an id; count it once")
        self.assertRegex(out, r"ruff==0\.16\.8 +PYSEC-2026-1 .*<- a version this PR introduces")
        self.assertIn("RESULT: FOUND -- 1 advisory", out)

    def test_an_advisory_on_another_fork_is_not_tagged_as_the_prs(self):
        """The PR moves one fork of rpds-py; the advisory is on the other, which it
        left alone. Tagged by name, the unchanged fork would read as the PR's."""
        pr = LOCK_PR.replace('version = "2026.6.3"', 'version = "2026.7.1"')
        export = EXPORT_PR.replace("rpds-py==2026.6.3", "rpds-py==2026.7.1")
        vuln = {"id": "PYSEC-2026-2", "fix_versions": [], "aliases": []}
        fake = Fake(
            locks={PR: pr, BASE: LOCK_BASE}, export=export, vulns={("rpds-py", "0.30.0"): [vuln]}
        )
        _, out, _ = self.go(fake)
        self.assertIn("rpds-py==2026.7.1   in the export", out)
        line = next(ln for ln in out.splitlines() if "PYSEC-2026-2" in ln)
        self.assertNotIn("this PR introduces", line)

    def test_a_skipped_pr_version_is_not_covered(self):
        code, out, _ = self.go(Fake(skip={("ruff", "0.16.8"): "Dependency not found on PyPI"}))
        self.assertEqual(code, 1)
        self.assertIn("ruff==0.16.8 (skipped by pip-audit)", out)

    def test_clean_means_every_pr_version_was_audited(self):
        code, out, _ = self.go(Fake())
        self.assertEqual(code, 0)
        self.assertIn("RESULT: CLEAN", out)
        self.assertIn("ruff==0.16.8   in the export", out)
        self.assertRegex(out, re.compile(r"OSV batch covers the whole lockfile"))


if __name__ == "__main__":
    unittest.main()
